insert into domicilio (id, calle, numero, localidad, provincia) values (1, 'Rutledge', '5204', 'Reading', 'Pennsylvania');
insert into domicilio (id, calle, numero, localidad, provincia) values (2, 'Haas', '3585', 'Buffalo', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (3, 'Kim', '4', 'Philadelphia', 'Pennsylvania');
insert into domicilio (id, calle, numero, localidad, provincia) values (4, 'Larry', '61', 'New York City', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (5, 'Lien', '8935', 'Pittsburgh', 'Pennsylvania');
insert into domicilio (id, calle, numero, localidad, provincia) values (6, 'Steensland', '367', 'Wilkes Barre', 'Pennsylvania');
insert into domicilio (id, calle, numero, localidad, provincia) values (7, 'Loftsgordon', '8654', 'New York City', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (8, 'Waubesa', '45622', 'Albany', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (9, 'Continental', '7', 'Albany', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (10, '1st', '21', 'Erie', 'Pennsylvania');
insert into domicilio (id, calle, numero, localidad, provincia) values (11, 'Clarendon', '10', 'Syracuse', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (12, 'Debs', '44759', 'Rochester', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (13, 'Carioca', '23379', 'Philadelphia', 'Pennsylvania');
insert into domicilio (id, calle, numero, localidad, provincia) values (14, 'Anniversary', '7949', 'Brooklyn', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (15, 'School', '29', 'Harrisburg', 'Pennsylvania');
insert into domicilio (id, calle, numero, localidad, provincia) values (16, 'David', '38515', 'Buffalo', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (17, 'Dixon', '4173', 'Erie', 'Pennsylvania');
insert into domicilio (id, calle, numero, localidad, provincia) values (18, 'Dottie', '34090', 'Buffalo', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (19, 'Independence', '7347', 'New York City', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (20, 'Forest', '7', 'Schenectady', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (21, 'Northwestern', '9305', 'Rochester', 'New York');
insert into domicilio (id, calle, numero, localidad, provincia) values (22, 'Fieldstone', '9', 'New York City', 'New York');
